export { default as Admin} from './Admin'
export { default as CreateAccount} from './CreateAccount'
export { default as DataPersonnel} from './DataPersonnel'
export { default as EditPassword} from './EditPassword'
export { default as HomeAdmin} from './HomeAdmin'